name: RobotAsAService
version: 0.1
# The vendor for the snap (replace 'Vendor <email@example.com>')
vendor: Kevin Carter <kevinmichaelcarter@outlook.com>
summary: Decentralised peer-to-peer robot timesharing
description: During a robot's downtime can be rented for work in its neighbourhod. Robot client publishes state and location data to a distributed network. It also controls behaviour and accepts instruction sets. User client transmits instruction sets and payment through the ethereum network. A Dapp locates the nearest robot and negotiates a rate for the work. Upon agreement the robot carries out the instruction set.

icon: icon.png

services:

stage:

parts:
 